# Generated by Django 5.0 on 2026-02-03 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_options_employee_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='allowed_late_minutes',
            field=models.IntegerField(default=10, help_text='Daqiqada (shu vaqtgacha jarima emas)', verbose_name='Ruxsat etilgan kechikish'),
        ),
        migrations.AddField(
            model_name='employee',
            name='daily_work_hours',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=4, verbose_name='Kunlik ish soatlari'),
        ),
        migrations.AddField(
            model_name='employee',
            name='late_penalty_per_minute',
            field=models.DecimalField(decimal_places=2, default=1000, help_text="So'mda (1 daqiqa kechikish uchun)", max_digits=10, verbose_name='Har bir daqiqa uchun jarima'),
        ),
        migrations.AddField(
            model_name='employee',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text="So'mda", max_digits=12, verbose_name='Oylik maosh'),
        ),
        migrations.CreateModel(
            name='MonthlySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('work_days', models.IntegerField(default=0)),
                ('present_days', models.IntegerField(default=0)),
                ('late_days', models.IntegerField(default=0)),
                ('absent_days', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Oylik maosh',
                'verbose_name_plural': 'Oylik maoshlar',
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
