# Generated by Django 5.0 on 2026-02-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_allowed_late_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='start_time',
        ),
        migrations.AddField(
            model_name='attendance',
            name='late_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('ontime', 'Vaqtida'), ('late', 'Kechikdi'), ('early', 'Erta keldi'), ('absent', "Kelgani yo'q"), ('day_off', 'Dam olish')], default='ontime', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_schedule',
            field=models.JSONField(default=dict, help_text='Masalan: {"monday": {"start": "09:00", "end": "18:00"}, "tuesday": ...}', verbose_name='Ish jadvali'),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='day_off_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date', 'type')},
        ),
        migrations.DeleteModel(
            name='DailyReport',
        ),
    ]
