# Generated by Django 5.0 on 2026-02-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_remove_employee_end_time_remove_employee_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('ontime', 'Vaqtida'), ('late', 'Kechikdi'), ('early', 'Erta keldi'), ('absent', 'Kelmagan'), ('day_off', 'Dam olish')], default='ontime', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='allowed_late_minutes',
            field=models.IntegerField(default=10, verbose_name='Ruxsat etilgan kechikish (daq.)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='late_penalty_per_minute',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name='Har daqiqa uchun jarima'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Oylik maosh'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_days',
            field=models.JSONField(default=list, verbose_name='Ish kunlari'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_schedule',
            field=models.JSONField(default=dict, verbose_name='Ish jadvali'),
        ),
    ]
