# Generated by Django 5.2.11 on 2026-02-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='total_late_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
