# Generated by Django 5.2.11 on 2026-02-17 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_monthlysalary_total_late_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('ontime', 'Vaqtida'), ('late', 'Kechikdi'), ('early', 'Erta keldi'), ('absent', 'Kelmagan'), ('day_off', 'Dam olish kuni')], default='ontime', max_length=10),
        ),
        migrations.CreateModel(
            name='ManualEntryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='manual_entries/%Y/%m/%d/')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_photos', to='employees.employee')),
            ],
            options={
                'verbose_name': "Qo'lda kiritilgan rasm",
                'verbose_name_plural': "Qo'lda kiritilgan rasmlar",
                'ordering': ['-captured_at'],
            },
        ),
    ]
