# Generated by Django 5.2.11 on 2026-02-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_alter_attendance_status_manualentryphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualentryphoto',
            name='attendance_type',
            field=models.CharField(choices=[('in', 'Kelish'), ('out', 'Chiqish')], default='in', max_length=3, verbose_name='Tur'),
        ),
    ]
