# Generated by Django 4.2 on 2026-06-07 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_manualentryphoto_attendance_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Lokatsiya nomi')),
                ('building', models.CharField(max_length=200, verbose_name='Bino nomi')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Kenglik (Latitude)')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Uzunlik (Longitude)')),
                ('radius_meters', models.PositiveIntegerField(default=100, verbose_name='Face ID masofasi (metr)')),
                ('branch_name', models.CharField(blank=True, max_length=200, verbose_name='Filial/Bino nomi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lokatsiya',
                'verbose_name_plural': 'Lokatsiyalar',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='face_photo',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_faces/%Y/%m/%d/', verbose_name='Yuz rasmi'),
        ),
        migrations.AddField(
            model_name='employee',
            name='cache_version',
            field=models.IntegerField(default=0, verbose_name='Kesh versiyasi'),
        ),
        migrations.CreateModel(
            name='FaceCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='face_captures/%Y/%m/%d/', verbose_name='Rasm')),
                ('attendance_type', models.CharField(choices=[('in', 'Kelish'), ('out', 'Chiqish')], max_length=3, verbose_name='Tur')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True, verbose_name='Olingan vaqt')),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_captures', to='employees.attendance', verbose_name='Davomat')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_captures', to='employees.employee', verbose_name='Xodim')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_captures', to='employees.location', verbose_name='Lokatsiya')),
            ],
            options={
                'verbose_name': 'Face ID rasm',
                'verbose_name_plural': 'Face ID rasmlar',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='LateAbsenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('late', 'Kechikish'), ('absent', 'Kelmagan')], max_length=10, verbose_name='Tur')),
                ('date', models.DateField(verbose_name='Sana')),
                ('late_minutes', models.PositiveIntegerField(default=0, verbose_name='Kechikish (daq.)')),
                ('reason', models.TextField(blank=True, verbose_name='Sabab')),
                ('admin_note', models.TextField(blank=True, verbose_name='Admin izohi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='late_absence_records', to='employees.attendance', verbose_name='Davomat')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_absence_records', to='employees.employee', verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Kechikish/Kelmaganlik',
                'verbose_name_plural': 'Kechikish/Kelmaganliklar',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date', 'record_type')},
            },
        ),
    ]
