# Generated by Django 4.2 on 2026-06-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_location_attendance_face_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Izoh'),
        ),
    ]
