# Generated by Django 4.2 on 2026-06-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_employee_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_enabled', models.BooleanField(default=False, verbose_name='Avtomatik tozalash yoqilgan')),
                ('months_back', models.PositiveIntegerField(default=2, verbose_name="Necha oydan eski ma'lumotlar")),
                ('interval_days', models.PositiveIntegerField(default=60, verbose_name='Oraliq (kun)')),
                ('clean_face_captures', models.BooleanField(default=True, verbose_name='Face ID rasmlar')),
                ('clean_attendance_photos', models.BooleanField(default=True, verbose_name='Davomat rasmlar')),
                ('clean_attendance_records', models.BooleanField(default=True, verbose_name='Davomat yozuvlari')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi tozalash')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Avtomatik tozalash sozlamasi',
                'verbose_name_plural': 'Avtomatik tozalash sozlamalari',
            },
        ),
    ]
